/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin(() => {
  const router = useRouter();
  const routesList = {
    slugEn: "slug___en",
    slugSw: "slug___sw",
    indexEn: "index___en",
    indexSw: "index___sw",
  };

  return {
    provide: {
      typedRouter: router as TypedRouter,
      routesList,
    },
  };
});
